apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: emsdevopsacr.azurecr.io/ems-employee:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  namespace: ems
spec:
  selector:
    app: employee
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
