name: EMS CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  # =========================
  # 1. Frontend CI
  # =========================
  frontend:
    name: Frontend - Build & Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/Emp-React

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/Emp-React/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build


  # =========================
  # 2. Spring Boot CI
  # =========================
  employee:
    name: Employee - Build & Test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:8
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: employee

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup Java 17
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build & Test
        env:
          MONGODB_URI: mongodb://localhost:27017/EMS
        run: ./mvnw clean verify

  # =========================
  # 3. Auth Backend CI
  # =========================
  auth-backend:
    name: Auth Backend - Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check Node application
        run: node --check server.mjs

  # =========================
  # 4. Security Scanning
  # =========================
  security:
    name: Security - Secrets, SAST & Dependencies
    runs-on: ubuntu-latest

    needs:
      - frontend
      - employee
      - auth-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      # Secret scanning
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Static Application Security Testing
      - name: Semgrep SAST
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d
        with:
          config: auto

      # Node.js dependency security
      - name: Install Auth Backend dependencies
        working-directory: Backend
        run: npm ci

      - name: npm audit
        working-directory: Backend
        run: npm audit --audit-level=high


  # =========================
  # 5. Docker Build & Push
  # =========================
  docker-build:
    name: Docker - Build & Push
    runs-on: ubuntu-latest

    needs:
      - frontend
      - employee
      - auth-backend
      - security

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Azure Login
        uses: azure/login@8216e11d8cd9b42fe925c852af8e76311ff067ac
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name emsdevopsacr

      - name: Build Frontend image
        run: |
          docker build \
            --build-arg VITE_EMPLOYEE_API_URL=/api \
            --build-arg VITE_AUTH_API_URL=/auth \
            -t emsdevopsacr.azurecr.io/ems-frontend:${{ github.sha }} \
            -t emsdevopsacr.azurecr.io/ems-frontend:latest \
            ./src/Emp-React

      - name: Build Employee image
        run: |
          docker build \
            -t emsdevopsacr.azurecr.io/ems-employee:${{ github.sha }} \
            -t emsdevopsacr.azurecr.io/ems-employee:latest \
            ./employee

      - name: Build Auth Backend image
        run: |
          docker build \
            -t emsdevopsacr.azurecr.io/ems-auth-backend:${{ github.sha }} \
            -t emsdevopsacr.azurecr.io/ems-auth-backend:latest \
            ./Backend

      - name: Push Frontend image
        run: |
          docker push emsdevopsacr.azurecr.io/ems-frontend:${{ github.sha }}
          docker push emsdevopsacr.azurecr.io/ems-frontend:latest

      - name: Push Employee image
        run: |
          docker push emsdevopsacr.azurecr.io/ems-employee:${{ github.sha }}
          docker push emsdevopsacr.azurecr.io/ems-employee:latest

      - name: Push Auth Backend image
        run: |
          docker push emsdevopsacr.azurecr.io/ems-auth-backend:${{ github.sha }}
          docker push emsdevopsacr.azurecr.io/ems-auth-backend:latest


  # =========================
  # 6. Deploy to AKS
  # =========================
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest

    needs:
      - docker-build

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Azure Login
        uses: azure/login@8216e11d8cd9b42fe925c852af8e76311ff067ac
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install kubectl
        uses: azure/setup-kubectl@c0c8b32d33a5244f1e5947304550403b63930415

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ems-devops-rg \
            --name ems-aks \
            --overwrite-existing

      - name: Deploy Git SHA images
        run: |
          kubectl -n ems set image deployment/frontend \
            frontend=emsdevopsacr.azurecr.io/ems-frontend:${{ github.sha }}

          kubectl -n ems set image deployment/employee \
            employee=emsdevopsacr.azurecr.io/ems-employee:${{ github.sha }}

          kubectl -n ems set image deployment/auth-backend \
            auth-backend=emsdevopsacr.azurecr.io/ems-auth-backend:${{ github.sha }}


      - name: Rollout frontend
        id: frontend-rollout
        continue-on-error: true
        run: |
          kubectl -n ems rollout status deployment/frontend --timeout=180s

      - name: Rollout employee
        id: employee-rollout
        continue-on-error: true
        run: |
          kubectl -n ems rollout status deployment/employee --timeout=180s

      - name: Rollout auth backend
        id: auth-rollout
        continue-on-error: true
        run: |
          kubectl -n ems rollout status deployment/auth-backend --timeout=180s

      - name: Rollback frontend
        if: steps.frontend-rollout.outcome == 'failure'
        run: |
          kubectl -n ems rollout undo deployment/frontend
          kubectl -n ems rollout status deployment/frontend --timeout=180s

      - name: Rollback employee
        if: steps.employee-rollout.outcome == 'failure'
        run: |
          kubectl -n ems rollout undo deployment/employee
          kubectl -n ems rollout status deployment/employee --timeout=180s

      - name: Rollback auth backend
        if: steps.auth-rollout.outcome == 'failure'
        run: |
          kubectl -n ems rollout undo deployment/auth-backend
          kubectl -n ems rollout status deployment/auth-backend --timeout=180s

      - name: Fail pipeline if deployment failed
        if: |
          steps.frontend-rollout.outcome == 'failure' ||
          steps.employee-rollout.outcome == 'failure' ||
          steps.auth-rollout.outcome == 'failure'
        run: |
          echo "One or more deployments failed."
          echo "Failed deployments were automatically rolled back."
          exit 1



      - name: Verify deployment
        run: |
          kubectl -n ems get deployments
          kubectl -n ems get pods
